# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151229_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='abertura',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
