# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151229_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ('-abertura',), 'verbose_name': 'chamado', 'verbose_name_plural': 'chamados'},
        ),
        migrations.AddField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='abertura',
            field=models.DateTimeField(verbose_name='abertura'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fechamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='problema',
            field=models.TextField(blank=True, null=True, verbose_name='problema'),
        ),
    ]
